### ISSUE TITLE
 java.lang.IllegalStateException: closed when loading image in recyclerview

### ISSUE THREAD

**Issue by safall** [coil-kt/coil#1674]
**Describe the bug**
Images are not loading in recycler view item. 
1 out of 10-12 image ends up in not loading with the stack trace below. 
It just loads placeholder, as the target throws in error block.
When scrolling the recycler view and scrolling back up, it loads the image in the same place again without any issue. 

**To Reproduce**
1. Open the list with images in recycler view.
2. Observe the recycler view some image are loading and some are not (usually 1 out of 1012 images dont load)
3. Scroll down the recycler view and scroll up again
4. Observe image loads again for item where previously not loaded.

**Logs/Screenshots**
![Screenshot 2023-03-22 at 13 56 58](https://user-images.githubusercontent.com/46202253/226911302-21f70ad8-d2d9-4b09-80f7-a5874a21df7b.png)

**Version**
Library version: 2.1.0
Android version: 13
Android device: Samsung galaxy s22

**Comment by colinrtwhite** [comment]
@safall This is very likely caused by sharing the directory between Picasso and Coil ([see here](https://github.com/coil-kt/coil/blob/main/coil-base/src/main/java/coil/disk/DiskCache.kt#L129)). Using separate folders for each disk cache should fix this.

**Comment by safall** [comment]
I created a new folder within `context.cacheDir` it didnt work. 
Then, I also tried storing it in somewhere else other than cacheDir, I see that the images are being cached. But the issue still persists. 

Then, I also let the internal disk cache to be used, and it works without any issues. 

So, its confusing either it is the problem with custom disk cache or something else.
